/**
 * GENERATED by PI-5D2A furniture Asset intake. Do not edit by hand.
 * Source: lib/afc-v2-runtime/furniture-asset-manifest.json
 * Regenerator: npm run vibode:generate-assets
 */

import type { CanonicalFurnitureAssetRecord } from "./furniture-asset-manifest-types";

export const GENERATED_FURNITURE_ASSETS: readonly CanonicalFurnitureAssetRecord[] =
  Object.freeze([
    Object.freeze({
      assetId: "afc-v2-runtime/test-fixtures/pi4a-sofa",
      glbUrl: "/afc-v2-runtime/test-fixtures/pi4a-sofa.glb",
      authoredWidthM: 2.2,
      authoredHeightM: 0.8,
      authoredDepthM: 0.9,
      status: "ready",
      sha256: "b4843b011fc2506b8b34ddead7571698df91b4ed7e4bde640dfec38e3de02e55",
    }),
    Object.freeze({
      assetId: "afc-v2-runtime/test-fixtures/pi5d-lounge-chair",
      glbUrl: "/afc-v2-runtime/test-fixtures/pi5d-lounge-chair.glb",
      authoredWidthM: 0.8,
      authoredHeightM: 0.8,
      authoredDepthM: 0.78,
      status: "ready",
      sha256: "d5eab07dc73bfd104d2dd8f31ff130676682978e3d9518762dbaa917ff02ee00",
    }),
    Object.freeze({
      assetId: "afc-v2-runtime/test-fixtures/pi5d2-side-table",
      glbUrl: "/afc-v2-runtime/test-fixtures/pi5d2-side-table.glb",
      authoredWidthM: 0.55,
      authoredHeightM: 0.46,
      authoredDepthM: 0.52,
      status: "ready",
      sha256: "00e8614d15d8d6871fbe8a2db5cd4f245b7d9f760e60c7aecb7f3d4bbf6cc418",
    }),
    Object.freeze({
      assetId: "afc-v2-runtime/partners/demo-furniture-co/demo-coffee-table-v1",
      glbUrl: "/afc-v2-runtime/partners/demo-furniture-co/demo-coffee-table-v1.glb",
      authoredWidthM: 1.2,
      authoredHeightM: 0.4,
      authoredDepthM: 0.6,
      status: "ready",
      sha256: "90b233c54433370c450ac34f6b5624e771615a71bfc31b3e60b91c64e9132c46",
    }),
    Object.freeze({
      assetId: "afc-v2-runtime/partners/demo-furniture-co/demo-side-table-v1",
      glbUrl: "/afc-v2-runtime/partners/demo-furniture-co/demo-side-table-v1.glb",
      authoredWidthM: 0.45,
      authoredHeightM: 0.55,
      authoredDepthM: 0.45,
      status: "ready",
      sha256: "e552f300e506c02810c59d99b8a2759da31e16fb45736f2310a0e73571d97338",
    }),
  ]);
