/**
 * Deterministic furniture Asset artifact generation.
 *
 * Canonical manifest → generated runtime registry TS.
 * SQL insert text is emitted at registration time from the same record.
 */

import type { CanonicalFurnitureAssetRecord } from "./furniture-asset-manifest-types";
import {
  FURNITURE_ASSET_MANIFEST_RELATIVE_PATH,
  furnitureAssetRepoPaths,
  writeFileAtomic,
} from "./furniture-asset-manifest";

function tsString(value: string): string {
  return JSON.stringify(value);
}

function tsNumber(value: number): string {
  return JSON.stringify(value);
}

export function renderGeneratedFurnitureAssetRegistry(
  assets: readonly CanonicalFurnitureAssetRecord[],
): string {
  const rows = assets.map((asset) => (
    `    Object.freeze({\n` +
    `      assetId: ${tsString(asset.assetId)},\n` +
    `      glbUrl: ${tsString(asset.glbUrl)},\n` +
    `      authoredWidthM: ${tsNumber(asset.authoredWidthM)},\n` +
    `      authoredHeightM: ${tsNumber(asset.authoredHeightM)},\n` +
    `      authoredDepthM: ${tsNumber(asset.authoredDepthM)},\n` +
    `      status: ${tsString(asset.status)},\n` +
    `      sha256: ${tsString(asset.sha256)},\n` +
    `    })`
  ));
  return (
    `/**\n` +
    ` * GENERATED by PI-5D2A furniture Asset intake. Do not edit by hand.\n` +
    ` * Source: ${FURNITURE_ASSET_MANIFEST_RELATIVE_PATH}\n` +
    ` * Regenerator: npm run vibode:generate-assets\n` +
    ` */\n` +
    `\n` +
    `import type { CanonicalFurnitureAssetRecord } from "./furniture-asset-manifest-types";\n` +
    `\n` +
    `export const GENERATED_FURNITURE_ASSETS: readonly CanonicalFurnitureAssetRecord[] =\n` +
    `  Object.freeze([\n` +
    `${rows.join(",\n")}${rows.length > 0 ? ",\n" : ""}` +
    `  ]);\n`
  );
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

export function renderFurnitureAssetInsertSql(
  asset: CanonicalFurnitureAssetRecord,
): string {
  return (
    `-- PI-5D2A: technical furniture Asset insert.\n` +
    `--\n` +
    `-- Inserts Asset metadata only. Does not create Product or Variant records.\n` +
    `-- Does not retarget existing Variants. Existing Scene Objects are not rewritten.\n` +
    `\n` +
    `begin;\n` +
    `\n` +
    `insert into public.vibode_stage_assets (\n` +
    `  asset_id,\n` +
    `  glb_url,\n` +
    `  authored_width_m,\n` +
    `  authored_height_m,\n` +
    `  authored_depth_m,\n` +
    `  status\n` +
    `) values (\n` +
    `  ${sqlString(asset.assetId)},\n` +
    `  ${sqlString(asset.glbUrl)},\n` +
    `  ${asset.authoredWidthM},\n` +
    `  ${asset.authoredHeightM},\n` +
    `  ${asset.authoredDepthM},\n` +
    `  ${sqlString(asset.status)}\n` +
    `);\n` +
    `\n` +
    `commit;\n`
  );
}

export function assetIdMigrationSlug(assetId: string): string {
  const last = assetId.split("/").pop() ?? "asset";
  return last.replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "").toLowerCase();
}

export function furnitureAssetMigrationFileName(
  timestamp: string,
  assetId: string,
): string {
  return `${timestamp}_vibode_stage_asset_${assetIdMigrationSlug(assetId)}.sql`;
}

export function isFurnitureAssetMigrationFileName(fileName: string): boolean {
  return /^\d{14}_vibode_stage_asset_[a-z0-9_]+\.sql$/.test(fileName);
}

export function writeGeneratedFurnitureAssetRegistry(
  repoRoot: string,
  assets: readonly CanonicalFurnitureAssetRecord[],
): string {
  const dest = furnitureAssetRepoPaths(repoRoot).generatedRegistry;
  writeFileAtomic(dest, renderGeneratedFurnitureAssetRegistry(assets));
  return dest;
}
