/**
 * GENERATED by PI-5E1 Product + default Variant registration. Do not edit by hand.
 * Regenerator: npm run vibode:register-product
 */

import type { StageProduct } from "./types";

export type GeneratedRegisteredVariant = Readonly<{
  variantId: string;
  productId: string;
  finishLabel: string | null;
  sku: string | null;
  priceAmount: number | null;
  priceCurrency: string;
  productUrl: string | null;
}>;

export const GENERATED_REGISTERED_PRODUCTS: readonly StageProduct[] =
  Object.freeze([
    Object.freeze({
      productId: "prod-vibode-studio-side-table",
      brand: "Vibode",
      name: "Studio Side Table",
      retailer: "Vibode",
      categoryId: "living-room",
      subcategoryId: "side-tables",
      productUrl: null,
      imageUrl: "/vibode-stage/studio-side-table.svg",
      priceAmount: 495,
      priceCurrency: "USD",
      defaultVariantId: "var-vibode-studio-side-table-default",
      collectionIds: Object.freeze(["col-vibode-picks"]),
      source: "vibode_curated",
      partnerId: null,
    }),
  ]);

export const GENERATED_REGISTERED_VARIANTS: readonly GeneratedRegisteredVariant[] =
  Object.freeze([
    Object.freeze({
      variantId: "var-vibode-studio-side-table-default",
      productId: "prod-vibode-studio-side-table",
      finishLabel: "Natural oak",
      sku: "VBD-STUDIO-SIDE-TABLE-01",
      priceAmount: 495,
      priceCurrency: "USD",
      productUrl: null,
    }),
    Object.freeze({
      variantId: "var-vibode-studio-side-table-walnut",
      productId: "prod-vibode-studio-side-table",
      finishLabel: "Walnut",
      sku: "VBD-STUDIO-SIDE-TABLE-WALNUT",
      priceAmount: 525,
      priceCurrency: "USD",
      productUrl: null,
    }),
    Object.freeze({
      variantId: "var-vibode-studio-side-table-black",
      productId: "prod-vibode-studio-side-table",
      finishLabel: "Black",
      sku: "VBD-STUDIO-SIDE-TABLE-BLACK",
      priceAmount: 495,
      priceCurrency: "USD",
      productUrl: null,
    }),
  ]);
