/**
 * GENERATED by PI-5D2B Variant → current Asset association. Do not edit by hand.
 * Regenerator: npm run vibode:retarget-variant
 */

export type GeneratedVariantCurrentAsset = Readonly<{
  variantId: string;
  productId: string;
  currentAssetId: string;
}>;

export const GENERATED_VARIANT_CURRENT_ASSETS: readonly GeneratedVariantCurrentAsset[] =
  Object.freeze([
    Object.freeze({
      variantId: "var-vibode-studio-chair-default",
      productId: "prod-vibode-studio-lounge-chair",
      currentAssetId: "afc-v2-runtime/test-fixtures/pi5d-lounge-chair",
    }),
    Object.freeze({
      variantId: "var-vibode-studio-settee-default",
      productId: "prod-vibode-studio-settee",
      currentAssetId: "afc-v2-runtime/test-fixtures/pi5d2-side-table",
    }),
    Object.freeze({
      variantId: "var-vibode-studio-side-table-black",
      productId: "prod-vibode-studio-side-table",
      currentAssetId: "afc-v2-runtime/test-fixtures/pi5d2-side-table",
    }),
    Object.freeze({
      variantId: "var-vibode-studio-side-table-default",
      productId: "prod-vibode-studio-side-table",
      currentAssetId: "afc-v2-runtime/test-fixtures/pi5d2-side-table",
    }),
    Object.freeze({
      variantId: "var-vibode-studio-side-table-walnut",
      productId: "prod-vibode-studio-side-table",
      currentAssetId: "afc-v2-runtime/test-fixtures/pi5d2-side-table",
    }),
    Object.freeze({
      variantId: "var-vibode-studio-sofa-default",
      productId: "prod-vibode-studio-sofa",
      currentAssetId: "afc-v2-runtime/test-fixtures/pi4a-sofa",
    }),
  ]);
