-- PI-2: immutable AFC production generations, durable EMPTY/TILED reuse,
-- room-level current successful generation pointer, private AFC Storage,
-- and lineage-safe activation.
--
-- AFC generations are independent of vibode_generation_runs (2D compositor).
-- EMPTY/TILED are not stage_output assets.
-- Tables are fail-closed under RLS; production APIs use the service role
-- after owner authorization.
--
-- Storage privacy invariant (bucket vibode-afc-v2):
--   anon          → no access
--   authenticated → no list / select / upload / update / delete
--                   and cannot mint usable AFC object URLs
--   service_role → production persistence access
--
-- Ready-row authority remains immutable. DELETE is allowed so
-- vibode_rooms ON DELETE CASCADE and authorized cleanup can succeed.
-- Browser roles are not granted table DELETE.

begin;

alter table public.vibode_rooms
  add column if not exists current_afc_generation_id uuid null;

create table public.vibode_afc_generations (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.vibode_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  parent_generation_id uuid null references public.vibode_afc_generations(id) on delete set null,
  lineage_seq bigint not null generated by default as identity (
    sequence name public.vibode_afc_generations_lineage_seq
  ),
  run_id text not null,
  intent text not null,
  status text not null,
  original_sha256 text null,
  original_decoded_width integer null,
  original_decoded_height integer null,
  original_byte_count integer null,
  original_mime_type text null,
  original_orientation smallint null,
  empty_sha256 text null,
  empty_decoded_width integer null,
  empty_decoded_height integer null,
  empty_byte_count integer null,
  empty_mime_type text null,
  empty_orientation smallint null,
  empty_storage_bucket text null,
  empty_storage_path text null,
  empty_artifact_source text null,
  tiled_sha256 text null,
  tiled_decoded_width integer null,
  tiled_decoded_height integer null,
  tiled_byte_count integer null,
  tiled_mime_type text null,
  tiled_orientation smallint null,
  tiled_storage_bucket text null,
  tiled_storage_path text null,
  tiled_artifact_source text null,
  tiled_cache_key text null,
  tiled_force_regeneration boolean not null default false,
  frame_width integer null,
  frame_height integer null,
  production_authority jsonb null,
  diagnostic_payload jsonb null,
  failure_reason text null,
  metric_status text null,
  collision_status text null,
  provider_provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz null,
  constraint vibode_afc_generations_intent_closed
    check (intent in ('analyze', 'run_again', 'reread_perspective')),
  constraint vibode_afc_generations_status_closed
    check (status in ('running', 'ready', 'failed')),
  constraint vibode_afc_generations_empty_source_closed
    check (
      empty_artifact_source is null
      or empty_artifact_source in ('durable', 'generated')
    ),
  constraint vibode_afc_generations_tiled_source_closed
    check (
      tiled_artifact_source is null
      or tiled_artifact_source in ('durable', 'generated')
    ),
  constraint vibode_afc_generations_run_id_key unique (run_id),
  constraint vibode_afc_generations_lineage_seq_key unique (lineage_seq)
);

create unique index vibode_afc_generations_room_id_id_idx
  on public.vibode_afc_generations (room_id, id);

create unique index vibode_afc_generations_room_lineage_seq_idx
  on public.vibode_afc_generations (room_id, lineage_seq);

alter table public.vibode_rooms
  add constraint vibode_rooms_current_afc_generation_id_fkey
    foreign key (current_afc_generation_id)
    references public.vibode_afc_generations(id)
    on delete set null;

create index vibode_afc_generations_room_created_desc_idx
  on public.vibode_afc_generations (room_id, created_at desc);

create index vibode_afc_generations_user_id_idx
  on public.vibode_afc_generations (user_id);

create table public.vibode_afc_durable_empty_artifacts (
  user_id uuid not null references auth.users(id) on delete cascade,
  original_sha256 text not null,
  empty_sha256 text not null,
  decoded_width integer not null,
  decoded_height integer not null,
  byte_count integer not null,
  mime_type text not null,
  orientation smallint not null default 1,
  storage_bucket text not null,
  storage_path text not null,
  source_generation_id uuid null references public.vibode_afc_generations(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (user_id, original_sha256)
);

create table public.vibode_afc_durable_tiled_artifacts (
  user_id uuid not null references auth.users(id) on delete cascade,
  cache_key text not null,
  empty_sha256 text not null,
  tiled_sha256 text not null,
  decoded_width integer not null,
  decoded_height integer not null,
  byte_count integer not null,
  mime_type text not null,
  orientation smallint not null default 1,
  storage_bucket text not null,
  storage_path text not null,
  generator_id text not null,
  profile_id text not null,
  research_preset text not null,
  requested_model_id text not null,
  empty_identity jsonb not null,
  tiled_identity jsonb not null,
  provenance jsonb not null,
  compatibility jsonb not null default '{}'::jsonb,
  source_generation_id uuid null references public.vibode_afc_generations(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (user_id, cache_key)
);

-- UPDATE immutability only. DELETE must succeed for room cascade / cleanup.
create or replace function public.vibode_afc_generations_protect_authority()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.lineage_seq is distinct from old.lineage_seq
    or new.room_id is distinct from old.room_id
    or new.user_id is distinct from old.user_id
    or new.run_id is distinct from old.run_id
  then
    raise exception 'AFC generation identity is immutable';
  end if;
  if old.status = 'ready' then
    if new.production_authority is distinct from old.production_authority
      or new.original_sha256 is distinct from old.original_sha256
      or new.empty_sha256 is distinct from old.empty_sha256
      or new.tiled_sha256 is distinct from old.tiled_sha256
      or new.frame_width is distinct from old.frame_width
      or new.frame_height is distinct from old.frame_height
      or new.intent is distinct from old.intent
    then
      raise exception 'AFC generation authority is immutable once ready';
    end if;
  end if;
  if old.status = 'failed' and new.status = 'ready' then
    raise exception 'AFC generation cannot be revived from failed to ready';
  end if;
  return new;
end;
$$;

drop trigger if exists vibode_afc_generations_protect_authority
  on public.vibode_afc_generations;

create trigger vibode_afc_generations_protect_authority
before update on public.vibode_afc_generations
for each row execute function public.vibode_afc_generations_protect_authority();

create or replace function public.protect_current_afc_generation_id()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'UPDATE'
    and new.current_afc_generation_id is distinct from old.current_afc_generation_id
    and auth.role() = 'authenticated'
  then
    raise exception 'current_afc_generation_id is server-managed';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_current_afc_generation_id
  on public.vibode_rooms;

create trigger protect_current_afc_generation_id
before update on public.vibode_rooms
for each row execute function public.protect_current_afc_generation_id();

-- Activate only when the candidate is newer than the current pointer.
-- Same generation is a no-op success. Older ready generations stay persisted
-- but do not become current.
create or replace function public.activate_vibode_afc_generation(
  p_room_id uuid,
  p_user_id uuid,
  p_generation_id uuid
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
  v_room uuid;
  v_user uuid;
  v_seq bigint;
  v_current uuid;
  v_current_seq bigint;
begin
  select r.current_afc_generation_id
    into v_current
  from public.vibode_rooms r
  where r.id = p_room_id
    and r.user_id = p_user_id
  for update;

  if not found then
    raise exception 'AFC room pointer update failed';
  end if;

  select g.status, g.room_id, g.user_id, g.lineage_seq
    into v_status, v_room, v_user, v_seq
  from public.vibode_afc_generations g
  where g.id = p_generation_id
  for update;

  if v_status is null then
    raise exception 'AFC generation not found';
  end if;
  if v_room is distinct from p_room_id or v_user is distinct from p_user_id then
    raise exception 'AFC generation does not belong to room owner';
  end if;
  if v_status is distinct from 'ready' then
    raise exception 'AFC generation is not production-ready';
  end if;

  if v_current is null or v_current = p_generation_id then
    update public.vibode_rooms
      set current_afc_generation_id = p_generation_id
    where id = p_room_id
      and user_id = p_user_id;
    return p_generation_id;
  end if;

  select g.lineage_seq
    into v_current_seq
  from public.vibode_afc_generations g
  where g.id = v_current
  for update;

  if v_current_seq is null or v_seq > v_current_seq then
    update public.vibode_rooms
      set current_afc_generation_id = p_generation_id
    where id = p_room_id
      and user_id = p_user_id;
    return p_generation_id;
  end if;

  return v_current;
end;
$$;

revoke all on function public.activate_vibode_afc_generation(uuid, uuid, uuid)
  from public, anon, authenticated;
grant execute on function public.activate_vibode_afc_generation(uuid, uuid, uuid)
  to service_role;

alter table public.vibode_afc_generations enable row level security;
alter table public.vibode_afc_durable_empty_artifacts enable row level security;
alter table public.vibode_afc_durable_tiled_artifacts enable row level security;

revoke all on table public.vibode_afc_generations from public, anon, authenticated;
revoke all on table public.vibode_afc_durable_empty_artifacts from public, anon, authenticated;
revoke all on table public.vibode_afc_durable_tiled_artifacts from public, anon, authenticated;

grant select, insert, update, delete on table public.vibode_afc_generations
  to service_role;
grant usage, select on sequence public.vibode_afc_generations_lineage_seq
  to service_role;
revoke all on sequence public.vibode_afc_generations_lineage_seq
  from public, anon, authenticated;
grant select, insert, update, delete on table public.vibode_afc_durable_empty_artifacts
  to service_role;
grant select, insert, update, delete on table public.vibode_afc_durable_empty_artifacts
  to service_role;
grant select, insert, update, delete on table public.vibode_afc_durable_tiled_artifacts
  to service_role;

-- Dedicated private AFC artifact bucket. ORIGINAL room photos remain in
-- vibode-base-images. AFC EMPTY/TILED/receipts never share that bucket.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vibode-afc-v2',
  'vibode-afc-v2',
  false,
  52428800,
  array['image/jpeg', 'image/png', 'image/webp', 'application/json']::text[]
);

-- Restrictive policies fail closed even if a dashboard policy later grants
-- authenticated access to "own folder" across buckets.
drop policy if exists vibode_afc_v2_deny_anon on storage.objects;
drop policy if exists vibode_afc_v2_deny_authenticated on storage.objects;

create policy vibode_afc_v2_deny_anon
on storage.objects
as restrictive
for all
to anon
using (bucket_id <> 'vibode-afc-v2')
with check (bucket_id <> 'vibode-afc-v2');

create policy vibode_afc_v2_deny_authenticated
on storage.objects
as restrictive
for all
to authenticated
using (bucket_id <> 'vibode-afc-v2')
with check (bucket_id <> 'vibode-afc-v2');

commit;
